x-common: &common
  working_dir: /go/src/microservice
  tty: true
  expose:
    - 8080
  command: sh -c "go run main.go"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf:/etc/nginx/vhost.d
    depends_on:
      - service-1
      - service-2
      - service-3

  termination:
    image: containous/whoami
    platform: linux/amd64 # プラットフォームを指定
    environment:
      - VIRTUAL_HOST=localhost

  service-1:
    <<: *common
    build:
      context: "./service-1"
    volumes:
      - ./service-1:/go/src/microservice

  service-2:
    <<: *common
    build:
      context: "./service-2"
    volumes:
      - ./service-2:/go/src/microservice

  service-3:
    <<: *common
    build:
      context: "./service-3"
    volumes:
      - ./service-3:/go/src/microservice
